[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling


In [9]:
import random
print(random.random(),'\n') # 0.0<= x < 1.0 사이 난수 리턴
print(random.randint(1,10),'\n') # 1 <= x <= 10 사이의 정수중에서 난수 값 리턴 
print(random.uniform(10,20),'\n') # min, max 사이 float 리턴
print(random.randrange(10),'\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li, 3), '\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.7290545927949408 

10 

14.017186499160076 

9 

2 

[5, 4, 2] 

[2, 4, 5, 1, 3]


In [12]:
import numpy as np
r = np.random.rand(100000000) # 0 ~ 1사이의 균일분포
# print(r)
r.mean()

0.5000294094378029

In [13]:
# 표준 정규분포
r = np.random.randn(10000)
print(r,'\n')
r.mean()

[-0.6993912  -0.89707774  0.36914919 ... -1.27017819  0.21105222
 -2.0952372 ] 



-0.0064149225209418955

In [14]:
np.random.uniform(1.0,2.0,10)

array([1.71183695, 1.79333158, 1.31491745, 1.61860188, 1.41090495,
       1.21823921, 1.17638505, 1.04098514, 1.12983252, 1.99478565])

In [15]:
np.random.uniform(0,1,(2,3))

array([[0.84588069, 0.68838881, 0.32071101],
       [0.83298678, 0.24579698, 0.25210208]])

In [16]:
# 0 ~ 1 사이의 난수 실수값으로 행렬 생성
# uniform 함수의 최소값, 최대값을 0,1로 지정한 것과 같음
np.random.random_sample((2,3))

array([[0.9656648 , 0.96161749, 0.75639457],
       [0.52083587, 0.78253907, 0.72574171]])

In [17]:
import pandas as pd
ar = np.random.rand(4,8)
ar

array([[0.13974041, 0.10880299, 0.01606359, 0.53585587, 0.31449617,
        0.90399085, 0.34880953, 0.18431546],
       [0.86408949, 0.1165452 , 0.2119467 , 0.29002673, 0.34150422,
        0.3768431 , 0.82101868, 0.83148415],
       [0.69691626, 0.34651134, 0.31026192, 0.21171038, 0.64089679,
        0.456993  , 0.11424349, 0.35065915],
       [0.98775606, 0.78112172, 0.48045988, 0.68850283, 0.61604792,
        0.36938727, 0.65743489, 0.7836027 ]])

In [ ]:
# 배열을 df로 변환
# coloumns 8개에 대한 이름# coloumns 8개에 대한 이름
columns = ['id','gender','age','region','product','price','qty','time']


In [19]:
df = pd.DataFrame(ar,columns=['id','gender','age','region','product','price','qty','time'])
df

id    gender       age    region   product     price       qty  \
0  0.139740  0.108803  0.016064  0.535856  0.314496  0.903991  0.348810   
1  0.864089  0.116545  0.211947  0.290027  0.341504  0.376843  0.821019   
2  0.696916  0.346511  0.310262  0.211710  0.640897  0.456993  0.114243   
3  0.987756  0.781122  0.480460  0.688503  0.616048  0.369387  0.657435   

       time  
0  0.184315  
1  0.831484  
2  0.350659  
3  0.783603

In [ ]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df3를 출력하세요.

In [22]:
df.id = np.random.randint(10,99,4)
df.gender = np.random.choice(['male','female'],4)
df.age = np.random.randint(0,100,4)
df[['id','gender','age']]

id  gender  age
0  30    male   73
1  74  female   56
2  79    male   58
3  80    male    6

In [26]:
# 배열에서 정렬한 후 50%에 해당하는 원소만 출력
large_ar = np.random.randn(1000000)
large_ar.sort()

In [27]:
large_ar[int(0.5*len(large_ar))]

-0.0007280381627879577

In [28]:
# 배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [29]:
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

['Bob', 'Joe', 'Will']

In [30]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 불리언 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [31]:
# 배열 데이터의 입출력
ar = np.arange(10)
np.save('some_ar',ar)

In [32]:
np.load('some_ar.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('ar_archive.npz', a=ar, b=ar)

In [35]:
arch = np.load('ar_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a = np.arange(1,10)
print(a,'\n')
np.argsort(a)

[1 2 3 4 5 6 7 8 9] 



array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [44]:
np.argsort(a)[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [39]:
# 인덱스 배열을 역순으로 출력
np.argsort(a)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

### 도전과제(7/6)
- np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.
- np.arange(4)을 이용해서 아래와 같이 출력하세요.

In [ ]:
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [45]:
# Q. 0 ~ 10 정수 (5,5)  행렬의 역행렬을 구한 후 두 행렬간의 행렬곱을 구하세요.
ar = np.random.randint(11,size=(5,5))
print(ar,'\n')
ar_r = np.linalg.inv(ar)
print(ar_r,'\n')
ar_d = np.dot(ar,ar_r)
print(ar_d)

[[ 2  4  7  0  2]
 [10 10  5  3  4]
 [10  5  3  0  6]
 [ 7  9  1  3  3]
 [ 1  7  1 10  7]] 

[[-1.87900875e-01  3.17638484e-01  2.91545190e-04 -2.54956268e-01
  -1.88046647e-02]
 [ 1.56268222e-01 -2.75801749e-01 -2.27405248e-02  3.86588921e-01
  -3.32361516e-02]
 [ 6.41399417e-02  1.77842566e-01 -4.66472303e-02 -2.06997085e-01
   8.74635569e-03]
 [-2.02623907e-01  4.15451895e-01 -1.25364431e-01 -3.68804665e-01
   8.60058309e-02]
 [ 1.50874636e-01 -3.88483965e-01  2.08454810e-01  2.06268222e-01
   5.46647230e-02]] 

[[ 1.00000000e+00 -1.11022302e-16 -1.11022302e-16 -2.22044605e-16
   2.77555756e-17]
 [-1.11022302e-16  1.00000000e+00  0.00000000e+00  2.22044605e-16
   2.77555756e-17]
 [-1.66533454e-16  0.00000000e+00  1.00000000e+00  0.00000000e+00
   6.93889390e-17]
 [ 8.32667268e-17 -4.44089210e-16 -5.55111512e-17  1.00000000e+00
   3.46944695e-17]
 [-2.49800181e-16  2.22044605e-16 -5.55111512e-17 -1.11022302e-16
   1.00000000e+00]]


### 과제(7/6-2) : 아래 가이드에 따라서 고객별 연간 구매데이터를 생성하고 아래사항을 수행하세요(관측치 1000개)

#### Q1. 고객 속성(id, 성별, 연령, 거주지역) 데이터와 거래 데이터를 통합한 데이터 프레임 df를 생성하세요.

거래 번호
- id : 1 ~ 1000번 일련번호 - 개시 후 1만 건의 거래가 있었고 걍 거기에 넘버링한 거라고 이해해보자

고객별 속성 데이터
- cusno : 고객번호 1000개 랜덤
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성

거래 데이터

- product_20 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- product_21 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- price_21 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- quantity_21 : 1 ~ 100 사이 정수 난수 생성

- amount_20 : price_20 * quantity_20
- amount_21 : price_21 * quantity_21
- sales : 20년 대비 21년구매금액이 증가면 1, 감소면 0

#### Q2. df를 수정하여 5가지 이상의 인사이트를 포함한 데이터 셋으로 변환하세요

#### Q3. df 를 탐색적 분석을 통하여 인사이트를 도출하세요.
