In [1]:
import numpy as np

In [11]:
# 1,2,3차원 배열 생성 및 차원 확인
arr1 = np.arange(8)
arr2 = arr1.reshape(2,4)
arr3 = arr1.reshape(2,2,2)
print(arr1,arr2,arr3,'\n')
print(f'{arr1.ndim}차원, {arr2.ndim}차원, {arr3.ndim}차원')


[0 1 2 3 4 5 6 7] [[0 1 2 3]
 [4 5 6 7]] [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 

1차원, 2차원, 3차원


In [12]:
print(a1.dtype)
a1 = arr1.astype('float64')
a1, a1.dtype

int32


(array([0., 1., 2., 3., 4., 5., 6., 7.]), dtype('float64'))

과제_0913_1. arange, zeros, ones로 배열을 다양하게 생성하세요.

In [15]:
# a1으로 1,2,3차원 배열을 만드세요.(reshape 사용)
a1 = np.arange(25)
a2 = a1.reshape(5,5)
a3 = a1.reshape(5,5,1)
print(a1,'\n')
print(a2,'\n')
print(a3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]
  [24]]]


과제_0913_2.
a1,a2,a3에서 원하는 원소값들을 다양한 방식으로 인덱싱하여 출력하세요.

In [16]:
# 불린 인덱싱
ar1d = np.arange(1,10)
ar1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# 불린 인덱싱 : [6, 7, 8, 9] 추출하세요.
ar = ar1d[ar1d > 5]
ar

array([6, 7, 8, 9])

In [20]:
# 일반 인덱싱
indexes = np.array([5,6,7,8])
ar = ar1d[indexes]
ar

array([6, 7, 8, 9])

In [23]:
# 정렬 
# np.sort() 원본 미반영
ar = np.array([3,1,9,5])
s1 = np.sort(ar)
print(s1)
print(ar)
# ndarray.sort() 정렬, 원본 반영
s2 = ar.sort()ㅠ
print(s2)
print(ar)

[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [24]:
# 내림차순
s1[::-1]

array([9, 5, 3, 1])

과제_0913_3. ar2d를 로우 방향, 컬럼 방향으로 정렬하세요.

In [25]:
ar2d = np.arange(9).reshape(3,3)
ar2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

In [29]:
# 선형대수 연산 - 행렬 내적
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
dot_product = np.dot(a,b)
dot_product

array([[ 58,  64],
       [139, 154]])

In [30]:
# 전치 행렬
print(a,'\n')
transpose_mat = np.transpose(a)
transpose_mat

[[1 2 3]
 [4 5 6]] 



array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
import pandas as pd
tdf = pd.read_csv('titanic_train.csv')
tdf.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [32]:
tdf.shape

(891, 12)

In [33]:
tdf.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [34]:
tdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [36]:
vcounts = tdf['Pclass'].value_counts()
vcounts

3    491
1    216
2    184
Name: Pclass, dtype: int64

과제_0913_5 데이터프레임과 리스트, 딕셔러리, ndarray 상호 변환 사례를 작성하여 설명하세요.

과제_0913_6.

tdf를 전처리 및 탐색적 분석(시각화, 통계적 기법)을 통하여 분석용 데이터셋으로 만드세요.

### 사이킷런을 이용하여 붓꽃(iris) 데이터 품종 예측하기

In [37]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [38]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [41]:
iris_data = iris.data
iris_label = iris.target
print(iris.feature_names,'\n')
print(iris.target_names,'\n')
print(iris_data,'\n')
print(iris_label)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] 

['setosa' 'versicolor' 'virginica'] 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5

In [43]:
idf = pd.DataFrame(iris_data,columns=iris.feature_names)
idf['label'] = iris.target
idf.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

과제_0913_7

idf에 대해서 학습용, 평가용 데이터를 8:2로 나누어서 분류 모델링(dt) 및 정확도 평가를 수행하세요