파이토치(PyTorch) 튜토리얼
https://tutorials.pytorch.kr/


# 파이토치(PyTorch)

* 페이스북이 초기 루아(Lua) 언어로 개발된 토치(Torch)를 파이썬 버전으로 개발하여 2017년도에 공개
* 초기에 토치(Torch)는 넘파이(NumPy) 라이브러리처럼 과학 연산을 위한 라이브러리로 공개
* 이후 GPU를 이용한 텐서 조작 및 동적 신경망 구축이 가능하도록 딥러닝 프레임워크로 발전시킴
* 파이썬답게 만들어졌고, 유연하면서도 가속화된 계산 속도를 제공


## 파이토치의 구성요소

- `torch`: 메인 네임스페이스, 텐서 등의 다양한 수학 함수가 포함
- `torch.autograd`: 자동 미분 기능을 제공하는 라이브러리
- `torch.nn`: 신경망 구축을 위한 데이터 구조나 레이어 등의 라이브러리
- `torch.multiprocessing`: 병럴처리 기능을 제공하는 라이브러리
- `torch.optim`: SGD(Stochastic Gradient Descent)를 중심으로 한 파라미터 최적화 알고리즘 제공
- `torch.utils`: 데이터 조작 등 유틸리티 기능 제공
- `torch.onnx`: ONNX(Open Neural Network Exchange), 서로 다른 프레임워크 간의 모델을 공유할 때 사용


## 텐서(Tensors)

* 데이터 표현을 위한 기본 구조로 텐서(tensor)를 사용
* 텐서는 데이터를 담기위한 컨테이너(container)로서 일반적으로 수치형 데이터를 저장
* 넘파이(NumPy)의 ndarray와 유사
* GPU를 사용한 연산 가속 가능


In [1]:
import torch

torch.__version__

'1.12.1+cu113'

In [2]:
x = torch.rand(4,2)
x

tensor([[0.1417, 0.7816],
        [0.1170, 0.2641],
        [0.3864, 0.9549],
        [0.9241, 0.9218]])

In [3]:
x = torch.zeros(4,2,dtype=torch.long)
x

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [5]:
x = torch.tensor([3,2.3])
x

tensor([3.0000, 2.3000])

In [7]:
x = x.new_ones(2,4,dtype=torch.double)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [10]:
print(x.size())
print(x.shape)

torch.Size([2, 4])
torch.Size([2, 4])


| Data type | dtype | CPU tensor | GPU tensor |
| ------ | ------ | ------ | ------ |
| 32-bit floating point | `torch.float32` or `torch.float` |`torch.FloatTensor` | `torch.cuda.FloatTensor` |
| 64-bit floating point | `torch.float64` or `torch.double` |`torch.DoubleTensor` | `torch.cuda.DoubleTensor` |
| 16-bit floating point | `torch.float16` or `torch.half` |`torch.HalfTensor` | `torch.cuda.HalfTensor` |
| 8-bit integer(unsinged) | `torch.uint8` |`torch.ByteTensor` | `torch.cuda.ByteTensor` |
| 8-bit integer(singed) | `torch.int8` |`torch.CharTensor` | `torch.cuda.CharTensor` |
| 16-bit integer(signed) | `torch.int16` or `torch.short` |`torch.ShortTensor` | `torch.cuda.ShortTensor` |
| 32-bit integer(signed) | `torch.int32` or `torch.int` |`torch.IntTensor` | `torch.cuda.IntTensor` |
| 64-bit integer(signed) | `torch.int64` or `torch.long` |`torch.LongTensor` | `torch.cuda.LongTensor` |


In [12]:
ft = torch.FloatTensor([1,2,3])
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [13]:
it = torch.IntTensor([1,2,3])
print(it)
print(it.dtype)


tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [14]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


### CUDA Tensors
- .to 메소드를 사용하여 텐서를 어떠한 장치(cpu, gpu)로도 옮길 수 있음

NVIDIA가 만든 병렬 컴퓨팅 플랫폼 및 API 모델로, 보통 '쿠다'라고 발음한다. CUDA 플랫폼은 GPU 의 가상 명령어셋을 사용할 수 있도록 만들어주는 소프트웨어 레이어이며, NVIDIA가 만든 CUDA 코어가 장착된 GPU에서 작동


In [15]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [16]:
# 0D Tensor
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


## 과제_1107_1 아래 Tensor들을 생성하세요.

In [ ]:
# 1D Tensor

In [ ]:
# 2D Tensor

In [ ]:
# 3D Tensor

In [ ]:
# 4D Tensor

In [ ]:
# 5D Tensor

### 과제_1107_2. numpy random으로 수행할 수 있는 형태를 설명하고 각 경우의 사례를 제시하세요.

### 과제_1107_3 아래 torch에서 활용하는 랜덤 값을 가지는 텐서와 특정한 값을 가지는 텐서 생성 사례를 제시하세요

º 랜덤한 값을 가지는 텐서 생성

1. torch.rand() : 0과 1 사이의 숫자를 균등하게 생성

2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

3. torch.randn() : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 생성

4. torch.randn_like() :  사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성, 자료형은 torch.float32

6. torch.randint_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

7. torch.randperm() : 주어진 범위 내의 정수를 랜덤하게 생성

º 특정한 값을 가지는 텐서 생성

1. torch.arange() : 주어진 범위 내의 정수를 순서대로 생성

2. torch.ones() : 주어진 사이즈의 1로 이루어진 텐서 생성

3. torch.zeros() : 주어진 사이즈의 0으로 이루어진 텐서 생성

4. torch.ones_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

5. torch.zeros_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

6. torch.linspace() : 시작점과 끝점을 주어진 갯수만큼 균등하게 나눈 간격점을 행벡터로 출력

7. torch.logspace() : 시작점과 끝점을 주어진 갯수만큼 로그간격으로 나눈 간격점을 행벡터로 출력


In [18]:
import math

a = torch.randn(1,2)
print(a)
b = a * 2 - 1
print(b)

tensor([[-1.4255, -0.2035]])
tensor([[-3.8510, -1.4070]])


In [19]:
# b에 대하여 min, max, mean, std, prod 을 구해보세요.

print(torch.min(b))
print(torch.max(b))
print(torch.mean(b))
print(torch.std(b))
print(torch.prod(b))
print(torch.unique(torch.tensor([1,2,3,1,2,1])))


tensor(-3.8510)
tensor(-1.4070)
tensor(-2.6290)
tensor(1.7282)
tensor(5.4186)
tensor([1, 2, 3])


In [20]:
x = torch.rand(2,2)
print(x)


tensor([[0.7097, 0.9583],
        [0.8216, 0.3094]])


In [22]:
print(x.max(dim=0),'\n')
print(x.max(dim=1))

torch.return_types.max(
values=tensor([0.8216, 0.9583]),
indices=tensor([1, 0])) 

torch.return_types.max(
values=tensor([0.9583, 0.8216]),
indices=tensor([1, 0]))


In [ ]:
# 4칙 연산 : add, sub, mul, div

In [24]:
x = torch.tensor([[1,2,3],[2,3,4]])
y = torch.tensor([[1,2,4],[2,3,5]])

print(x)
print(y, '\n')

print(torch.add(x,y),'\n')
print(torch.sub(x,y),'\n')
print(torch.mul(x,y),'\n')
print(torch.div(x,y))


tensor([[1, 2, 3],
        [2, 3, 4]])
tensor([[1, 2, 4],
        [2, 3, 5]]) 

tensor([[2, 4, 7],
        [4, 6, 9]]) 

tensor([[ 0,  0, -1],
        [ 0,  0, -1]]) 

tensor([[ 1,  4, 12],
        [ 4,  9, 20]]) 

tensor([[1.0000, 1.0000, 0.7500],
        [1.0000, 1.0000, 0.8000]])


### 과제_1107_4.
2D Tensor x,y를 생성한 후 x,y의 내적을 구하세요.(torch.matmul 혹은 torch.mm을 사용)

### 과제_1107_5.
위에서 구한 내적 결과를 특이값 분해하여 U, S, V Tensor를 구하세요.